# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\x12\tmyservice\"&\n\rNestedMessage\x12\x15\n\rinner_message\x18\x01 \x01(\t\"\xd7\x01\n\tMyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07numbers\x18\x02 \x03(\x05\x12@\n\x0fkey_value_pairs\x18\x03 \x03(\x0b\x32\'.myservice.MyRequest.KeyValuePairsEntry\x12\x30\n\x0enested_message\x18\x04 \x01(\x0b\x32\x18.myservice.NestedMessage\x1a\x34\n\x12KeyValuePairsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"O\n\nMyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x30\n\x0enested_message\x18\x02 \x01(\x0b\x32\x18.myservice.NestedMessage2G\n\tMyService\x12:\n\x0bSendMessage\x12\x14.myservice.MyRequest\x1a\x15.myservice.MyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _MYREQUEST_KEYVALUEPAIRSENTRY._options = None
  _MYREQUEST_KEYVALUEPAIRSENTRY._serialized_options = b'8\001'
  _globals['_NESTEDMESSAGE']._serialized_start=31
  _globals['_NESTEDMESSAGE']._serialized_end=69
  _globals['_MYREQUEST']._serialized_start=72
  _globals['_MYREQUEST']._serialized_end=287
  _globals['_MYREQUEST_KEYVALUEPAIRSENTRY']._serialized_start=235
  _globals['_MYREQUEST_KEYVALUEPAIRSENTRY']._serialized_end=287
  _globals['_MYRESPONSE']._serialized_start=289
  _globals['_MYRESPONSE']._serialized_end=368
  _globals['_MYSERVICE']._serialized_start=370
  _globals['_MYSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
