version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/heartbeat"]
      interval: 10s
      timeout: 3s
      retries: 3
  redis:
    image: "redis:alpine"
